### ISSUE TITLE
bug with OneCycleLR on Apple Silicone 

### ISSUE THREAD

**Issue by jopeptid** [pyro-ppl/pyro#3166]
### Guidelines

**NOTE:** Issues are for bugs and feature requests only. If you have a question about using Pyro or general modeling questions, please post it on the [forum](https://forum.pyro.ai/).

If you would like to address any minor bugs in the documentation or source, please feel free to contribute a Pull Request without creating an issue first. 

Please tag the issue appropriately in the title e.g. [bug], [feature request], [discussion], etc.

Please provide the following details:
--------------------------------------------------------------------------------------------------
### Issue Description
Provide a brief description of the issue.

### Environment
For any bugs, please provide the following:
 - OS and python version.
 - PyTorch version, or if relevant, output of `pip freeze`.
 - Pyro version: output of `python -c 'import pyro; print pyro.__version__'`

### Code Snippet
Provide any relevant code snippets and commands run to replicate the issue.

**Comment by jopeptid** [comment]
Hi,

I got stuck on this for a couple of weeks now. The bug appears on a Apple Silicone install and the same code runs fine on a Ubuntu box.

MacOS Ventura 13.1
pyro-ppl    1.8.3+3422c3a4
pytorch     2.0.0.dev2022121
(I get the error on several pytorch releases tested over the last month)

code:
Python 3.8.15 | packaged by conda-forge | (default, Nov 22 2022, 08:53:40)
[Clang 14.0.6 ] on darwin
>>> from torch.optim.lr_scheduler import OneCycleLR    # This works and I can use the scheduler on some test data

# If I trie instead:
from pyro.optim import OneCycleLR
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'OneCycleLR' from 'pyro.optim' (/Users/JA/anaconda3/envs/torch-gpu/lib/python3.8/site-packages/pyro/optim/__init__.py)

Thank you for looking into this.

**Comment by eb8680** [comment]
@jopeptid thanks for the report, I ran into this today as well. Fortunately, I don't think this has anything to do with Apple Silicon, it's just a small breaking change in PyTorch nightlies with an easy fix in #3167
